/ik_moveit:
  ros__parameters:
    vm: true
    fps_moveit_plan: 40.0
    fps_aubo_query: 40.0
    fps_aubo_consume: 200.0
    latency_hand_to_before_plan: 0.030
    # there is time to wait for queue!!
    latency_after_plan_others: 0.030
    size_expected_mac_points: 60 # should least 50
    pos_filter_q_x: 0.01
    pos_filter_q_v: 100.0
    pos_filter_r_x: 10.0
