ik_moveit_right:
  ros__parameters:
    # [vr and hand]
    vr_idx: 0
    hand_y_offset: 0.0
    # [control]
    check_joint_broadcaster: false
    fps_moveit_plan: 94.0
    fps_aubo_query: 100.0
    fps_aubo_consume: 200.0
    mirror_the_hand: false # 左臂反转 y
    # there is time to wait for queue!!
    size_expected_mac_points: 7 # should least 50
    # [precition]
    pos_filter:
      enabled: false
      prediction: false
      q:
        x: 0.1
        v: 100.0
      r:
        x: 50.0
    latency:
      hand_to_before_plan: 0.028
      after_plan_others: 0.048
    # max vel and max acc
    joints_deg_max_vel: [150.0, 150.0, 150.0, 240.0, 240.0, 240.0]
    joints_deg_max_acc: [200.0, 200.0, 200.0, 200.0, 200.0, 200.0]
    # 每帧 1 / 200s 最多变化 50 ?
    joints_deg_max_jerk: [40000.0, 40000.0, 40000.0, 40000.0, 40000.0, 40000.0]
    joints_jump_deg: 40.0
    joints_jump_limit_rate: 0.03
    control_deg_eps: 0.001
    # hand min diff for planning
    hand_pos_min_diff_to_plan: 0.000
    hand_deg_min_diff_to_plan: 0.01
    # [ik] kdl, internal
    ik_method: "internal"
    # [plan mode]
    # no, init_point, normal, linear, sin
    plan_mode: "sin" 
    # [plan mode.linear]
    plan_mode_linear:
      A: [0.4, -0.4, 0.3]
      B: [0.4, +0.2, 0.3]
      half_t: 2.0
    # [plan mode.normal]
    plan_mode_normal:
      q_up: true
    launchtime_debug_queue_size: 5000
    # [aubo ip]
    aubo_service_port: 8899


/**:
  ros__parameters:
    # [meta]
    group_name: "right_dual2"
    aubo_ip: "192.168.1.7"
